"""Stable names and paths in tests/fixtures/sample-project."""

HELPER_FILE = "src/helper.ts"
WIDGET_FILE = "src/widget.ts"
USER_FILE = "src/user.ts"
CONSUMER_FILE = "src/consumer.ts"
LIB_HANDLER_FILE = "src/lib/handler.ts"
APP_HANDLER_FILE = "src/app/handler.ts"

FN_GREET = "greet"
CLASS_WIDGET = "Widget"
TYPE_OPTIONS = "Options"
FIELD_VERBOSE = "verbose"
CLASS_HANDLER = "Handler"
CONST_VERSION = "VERSION"
FN_ORPHAN = "orphanExport"
METHOD_RUN = "Widget.run"

# Analyze pattern fixture paths
LAZY_PANEL_FILE = "src/ui/LazyPanel.ts"
PANEL_PAGE_FILE = "src/pages/panelPage.ts"
CACHE_HELPERS_FILE = "src/lib/cacheHelpers.ts"
GATEWAY_FILE = "src/gateway/index.ts"
INFERENCE_CLIENT_FILE = "src/integrations/inferenceClient.ts"
ORPHAN_WIDGET_FILE = "src/widgets/OrphanWidget.ts"
STREAM_TYPES_FILE = "src/events/streamTypes.ts"
LABELS_FILE = "src/domain/labels/index.ts"
TYPE_A_FILE = "src/types/a.ts"
TYPE_B_FILE = "src/types/b.ts"
I18N_EN_FILE = "src/domain/i18n/en.ts"
I18N_INDEX_FILE = "src/domain/i18n/index.ts"
BUTTON_FILE = "src/ui/Button.ts"
HOOK_A_FILE = "src/hooks/useHookA.ts"
HOOK_B_FILE = "src/hooks/useHookB.ts"

FN_LAZY_PANEL = "LazyPanel"
FN_EVICT_ITEM = "evictItem"
FN_SEND = "send"
CLASS_INFERENCE_CLIENT = "InferenceClient"
FN_ORPHAN_WIDGET = "OrphanWidget"
TYPE_BASE_STREAM = "BaseStream"
TYPE_LABEL_FUNC = "LabelFunc"
TYPE_BUTTON_PROPS = "ButtonProps"
TYPE_OPTS = "Opts"
